function MIX = importfile(workbookFile, sheetName, startRow, endRow)
%IMPORTFILE4 Import data from a spreadsheet
%  MIX = IMPORTFILE4(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  MIX = IMPORTFILE4(FILE, SHEET) reads from the specified worksheet.
%
%  MIX = IMPORTFILE4(FILE, SHEET, STARTROW, ENDROW) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  STARTROW and ENDROW as a pair of scalars or vectors of matching size
%  for dis-contiguous row intervals.
%
%  Example:
%  MIX = importfile4("/Users/ailguestuser/Desktop/Danny_mixedVA/MIX.F017.1_2018-10-18_Scientific_Report_2019-06-24.xlsx", "Sheet1", 85, 228);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Aug-2019 10:36:18

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 85;
    endRow = 228;
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + startRow(1) + ":O" + endRow(1);

% Specify column names and types
opts.VariableNames = ["Times", "Meancms", "Maxcms", "Mincms", "SDcms", "Sumcms", "Areamm", "FlowRatemls", "PositiveSumcms", "NegativeSumcms", "PositiveAreamm", "NegativeAreamm", "NetPositiveFlowRatemls", "NetNegativeFlowRatemls", "Contour"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical"];
opts = setvaropts(opts, 15, "EmptyFieldRule", "auto");

% Setup rules for import
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts = setvaropts(opts, [1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14], "TreatAsMissing", '');

% Import the data
MIX = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:length(startRow)
    opts.DataRange = "A" + startRow(idx) + ":O" + endRow(idx);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    MIX = [MIX; tb]; %#ok<AGROW>
end

end